name: Generate Snake Game SVG

on:
  schedule:
    - cron: "0 0 * * 0" # every week
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: erzer12
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git diff --staged --quiet || (git commit -m "Update contribution graph with snake animation" && git push)
