name: Update README and 3D Contribution Map

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate 3D Contribution Map
      run: |
        mkdir -p profile-3d-contrib
        curl -o profile-3d-contrib/profile-night-rainbow.svg https://ghchart.rshah.org/erzer12

    - name: Fetch All Repositories and Calculate Languages
      id: languages
      env:
        PAT: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
      run: |
        # Fetch all repositories for the user
        curl -s -H "Authorization: Bearer $PAT" "https://api.github.com/user/repos?per_page=100" > repos.json

        # Initialize an empty file for language statistics
        echo "" > languages.txt

        # Loop through each repository and fetch language data
        for repo in $(jq -r '.[].languages_url' repos.json); do
          curl -s -H "Authorization: Bearer $PAT" "$repo" >> languages.txt
        done

        # Extract and count languages
        jq -r 'keys_unsorted[]' languages.txt | sort | uniq -c | sort -nr > aggregated_languages.txt

    - name: Update README.md
      run: |
        # Extract top 5 languages
        LANGUAGES=$(cat aggregated_languages.txt | awk '{print $2 " (" $1 ")"}' | head -5 | tr '\n' ',' | sed 's/,$//')

        # Replace placeholder in README.md
        sed -i "s|<!--LANGUAGES-->.*<!--/LANGUAGES-->|<!--LANGUAGES-->$LANGUAGES<!--/LANGUAGES-->|" README.md

    - name: Commit and Push Changes
      env:
        PAT: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
        
        # Add all files (tracked and untracked) to the commit
        git add profile-3d-contrib/profile-night-rainbow.svg README.md aggregated_languages.txt languages.txt repos.json
        git commit -m 'Update README with Most Used Languages and 3D Contribution Map'
        git push
