name: Update Top Languages SVG

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly
  workflow_dispatch:

jobs:
  update-top-langs-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install requests svgwrite

      - name: Generate top languages SVG
        run: python .github/scripts/generate_top_langs_svg.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add top-langs.svg
          git diff --staged --quiet || (git commit -m "Update top languages SVG" && git push)
